def check_vowels():
    texto = input("Ingrese un nombre: ")
    print("a" in texto.lower())
    print("e" in texto.lower())
    print("i" in texto.lower())
    print("o" in texto.lower())
    print("u" in texto.lower())
    texto = input("Ingrese un nombre: ")
    print("a" in texto.lower())
    print("e" in texto.lower())
    print("i" in texto.lower())
    print("o" in texto.lower())
    print("u" in texto.lower())
check_vowels()
